def Criba(n):                                   # O(1)
    primo[0] = primo[1] = False                     # O(1)
    i = 2                                           # O(1)
    while i * i <= n:                               # O(√n)
        if primo[i]:                                    # O(1)            
            for j in range(i * i, n+1, i):                  # O(n/i)
                primo[j] = False                            # O(1)
        i = i + 1                                       # O(1)

n = 25                      # O(1) 
primo = [True] * (n+2)      # O(n)             
Criba(n)                    # O(n log(log(n)))  

for i in range(2, n):       # O(n)  
    if primo[i]:                # O(1)  
        print(i)                    # O(1)  